accounts_app/urls.py
from django.urls import path

from accounts_app.views import dashboard, UserListView, delete_user_post, AdminListView, \
    add_remove_admin, active_de_active_user, UserBlockListView, create_new_user, edit_user_profile, \
    change_password_from_admin, edit_post, delete_skill, ArticleListView, category_list, category_edit, create_category, \
    article_filter, tag_list, create_tag, delete_tag, delete_category, tag_edit, create_article, delete_article, \
    article_gallery, gallery_list, remove_gallery, edit_article_gallery, seo_for_article_list, \
    delete_seo_for_article_list, create_seo_for_article_list, edit_seo_for_article_list, post_seo_list, \
    edit_article_seo, create_article_seo, delete_seo, suggestion_post_list, create_suggestion_post, \
    delete_suggestion_post, comment_list, edit_comment, delete_comment, sliders, edit_slider, login_view, delete_slider, \
    subscribe
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/create-new-user/', create_new_user, name='create-new-user'),
    path('dashboard/user-list/', UserListView.as_view(), name='user-list'),
    path('dashboard/admin-list/', AdminListView.as_view(), name='admin-list'),
    path('dashboard/block-list/', UserBlockListView.as_view(), name='block-list'),
    path('dashboard/edit-user/<int:pk>/delete-post/<int:post_id>/', delete_user_post, name='delete-user-post'),
    path('dashboard/edit-user/<int:user_id>/', edit_user_profile, name='edit-user'),
    path('dashboard/add-remove-admin/<int:user_id>/', add_remove_admin, name='add-remove-admin'),
    path('dashboard/active-deactive-user/<int:user_id>/', active_de_active_user, name='active-deactive-user'),
    path('login/', login_view, name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/accounts/login.html'), name='logout'),
    path('change-password/<int:user_id>/', change_password_from_admin, name='change-password-from-admin'),
    path('edit-article/<int:post_id>/', edit_post, name='edit-article'),
    path('edit-user/delete-skill/<int:user_id>/<int:skill_id>/', delete_skill, name='delete-skill'),
    path('article-list/', ArticleListView.as_view(), name='article-list'),
    path('article-list/filter/<str:filter_name>/', article_filter, name='article-filter'),
    path('category-list/', category_list, name='category-list'),
    path('tag-list/', tag_list, name='tag-list'),
    path('category-edit/<int:category_id>/change/', category_edit, name='category-edit'),
    path('tag-edit/<int:tag_id>/change/', tag_edit, name='tag-edit'),
    path('create-category/new/', create_category, name='create-category'),
    path('create-tag/new/', create_tag, name='create-tag'),
    path('delete-tag/<int:tag_id>/', delete_tag, name='delete-tag'),
    path('delete-category/<int:category_id>/', delete_category, name='delete-category'),
    path('create-article/new/', create_article, name='create-article'),
    path('delete-article/<int:article_id>/', delete_article, name='delete-article'),
    path('gallery-list/', gallery_list, name='gallery-list'),
    path('create-gallery/', article_gallery, name='create-gallery'),
    path('remove-gallery/<int:gallery_id>/', remove_gallery, name='remove-gallery'),
    path('edit-gallery/<int:gallery_id>/', edit_article_gallery, name='edit-gallery'),
    path('seo-listArticle/', seo_for_article_list, name='seo-articleList'),
    path('delete-seo-listArticle/<int:seo_id>/', delete_seo_for_article_list, name='delete-seo-articleList'),
    path('edit-seo-listArticle/<int:seo_id>/', edit_seo_for_article_list, name='edit-seo-articleList'),
    path('create_seo_for_article_list/', create_seo_for_article_list, name='create_seo_for_article_list'),
    path('post-seo-list/', post_seo_list, name='post-seo-list'),
    path('edit-article-seo/<int:article_id>/', edit_article_seo, name='edit-article-seo'),
    path('create-article-seo/', create_article_seo, name='create-article-seo'),
    path('delete-seo/<int:seo_id>/', delete_seo, name='delete-seo'),
    path('suggestion-post-list/', suggestion_post_list, name='suggestion-post-list'),
    path('create-suggestion-post/', create_suggestion_post, name='create-suggestion-post'),
    path('delete-suggestion-post/<int:post_id>/', delete_suggestion_post, name='delete-suggestion-post'),
    path('delete-comment/<int:comment_id>/', delete_comment, name='delete-comment'),
    path('comments/', comment_list, name='comments'),
    path('edit-comment/<int:comment_id>/', edit_comment, name='edit-comment'),
    path('sliders/', sliders, name='sliders'),
    path('sliders/edit/<int:slider_id>/', edit_slider, name='edit-slider'),
    path('delete-slider/<int:slider_id>/', delete_slider, name='delete-slider'),
    path('subscribes/', subscribe, name='subscribes'),

]

api/urls.py
from django.urls import path

from api.views import ArticleListApiView, ArticleDetailApiView, ArticleUpdateApiView, ArticleDeleteApiView, \
    CreateArticleApiView

app_name = 'api'
urlpatterns = [
    path('', ArticleListApiView.as_view(), name='api-article-list'),
    path('create-article/', CreateArticleApiView.as_view(), name='api-create-article'),
    path('<int:pk>/', ArticleDetailApiView.as_view(), name='api-article-detail'),
    path('<int:pk>/update/', ArticleUpdateApiView.as_view(), name='api-article-update'),
    path('<int:pk>/delete/', ArticleDeleteApiView.as_view(), name='api-article-delete'),
]

blog_app/urls.py
from django.urls import path

from blog_app.views import ArticleListView, article_detail_view, Search, GetByCategory, GetByTag

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('<int:article_id>/<title>/', article_detail_view, name='article_detail'),
    path('search/', Search.as_view(), name='search'),
    path('categories/<slug:category_name>/', GetByCategory.as_view(), name='get_category'),
    path('tags/<slug:tag_name>/', GetByTag.as_view(), name='get_tag'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('', home_page, name='home-page'),
    path('accounts/', include('accounts_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('about-us/', include('aboutUs_app.urls')),
    path('contact-us/', include('contact_us_app.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts_app/forms.py
from django import forms
from django.core import validators
from django.utils import html
from accounts_app.models import CustomUser
from tinymce.widgets import TinyMCE
from blog_app.models import Category, Tag, Article
from slider_app.models import Slider


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control d-block', 'placeholder': 'نام کاربری را وارد کنید'}),
        label='نام کاربری')
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'رمز عبور خود را وارد کنید'}),
        label='رمز عبور')
    remember_me = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-control'}), required=False,
                                     label='مرا به خاطر بسپار')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if CustomUser.objects.filter(username=username).exists():
            return username
        else:
            raise forms.ValidationError('نام کاربری یا رمز عبور اشتباه است')


class CreateNewUserForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'username', 'placeholder': 'نام کاربری را وارد کنید'}),
        label='نام کاربری',
        validators=[
            validators.MinLengthValidator(3, 'نام کاربری باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(12, 'نام کاربری باید کمتر از 12 کلمه باشد')
        ],
        required=True,
        max_length=12,
        min_length=3,
        help_text="حروف انگلیسی و اعداد حروف _،@،# مجاز است (12 کلمه مجاز میباشد)"
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'id': 'password1', 'placeholder': 'رمز عبور را وارد کنید'}),
        label='رمز عبور',
        validators=[
            validators.MinLengthValidator(12, 'رمز عبور باید  12 کلمه باشد.'),
            validators.MaxLengthValidator(12, 'رمز عبور باید 12 کلمه باشد')
        ],
        required=True,
        max_length=12,
        min_length=12,
        help_text=html.format_html(
            '<div class="help"><ul class="list-unstyled text-secondary"><li>گذرواژه شما نمی‌تواند شبیه سایر اطلاعات شخصی شما باشد.</li><li>رمز عبور شما می‌بایست حداقل از 8 حرف تشکیل شده باشد.</li><li>گذرواژه شما نمی تواند یک گذرواژه معمول باشد.</li><li>گذرواژه شما نمی تواند کلا عدد باشد</li></ul></div>')

    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'id': 'password2', 'placeholder': 'تکرار رمز عبور را وارد کنید'}),
        label='تکرار رمز عبور',
        validators=[
            validators.MinLengthValidator(12, 'تکرار رمز عبور باید  12 کلمه باشد.'),
            validators.MaxLengthValidator(12, 'تکرار رمز عبور باید  12 کلمه باشد')
        ],
        required=True,
        max_length=12,
        min_length=12,
        help_text="برای تائید، رمز عبور قبلی را وارد کنید."
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        user = CustomUser.objects.filter(username=username).exists()
        if user:
            raise forms.ValidationError('نام کاریری قبلا ثبت شده')
        else:
            return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password2 != password1:
            raise forms.ValidationError('رمز عبور و تکرار آن، یکی نیستند')
        else:
            return password1


class EditUserProfileForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'first_name', 'placeholder': 'نام را وارد کنید'}),
        label='نام',
        validators=[
            validators.MinLengthValidator(3, 'نام باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(200, 'نام باید کمتر از 200 کلمه باشد')
        ],
        required=False,
        max_length=200,
        min_length=3,
        help_text="نام کوچک خود را وارد کنید"
    )

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'last_name', 'placeholder': 'نام خانوادگی را وارد کنید'}),
        label='نام خانوادگی',
        validators=[
            validators.MinLengthValidator(3, 'نام خانوادگی باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(200, 'نام خانوادگی باید کمتر از 200 کلمه باشد')
        ],
        required=False,
        max_length=200,
        min_length=3,
        help_text="نام خانوادگی خود را وارد کنید"
    )

    profile_image = forms.ImageField(required=False,
                                     help_text='برای خود عکسی انتخاب کنید ( حداکثر اندازه 1 مگابایت است.(1MB) )',
                                     label='تصویر پروفایل')

    education = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'education', 'placeholder': 'تحصیلات را وارد کنید'}),
        label='تحصیلات',
        validators=[
            validators.MinLengthValidator(3, 'تحصیلات باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(200, 'تحصیلات باید کمتر از 200 کلمه باشد')
        ],
        required=False,
        max_length=200,
        min_length=3,
        help_text="تحصیلات خود را وارد کنید"
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'address', 'placeholder': 'آدرس کنونی را وارد کنید'}),
        label='آدرس کنونی',
        validators=[
            validators.MinLengthValidator(3, 'آدرس کنونی باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(200, 'آدرس کنونی باید کمتر از 200 کلمه باشد')
        ],
        required=False,
        max_length=200,
        min_length=3,
        help_text="آدرس کنونی خود را وارد کنید"
    )

    about_me = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'about_me', 'placeholder': 'درباره من را وارد کنید'}),
        label='درباره من',
        validators=[
            validators.MinLengthValidator(3, 'درباره من باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(200, 'درباره من باید کمتر از 200 کلمه باشد')
        ],
        required=False,
        max_length=200,
        min_length=3,
        help_text="درباره ی خود چیزی بنویسید"
    )

    my_skill = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'id': 'my_skill', 'placeholder': 'مهارت های من را وارد کنید'}),
        label='مهارت های من',
        validators=[
            validators.MinLengthValidator(3, 'مهارت های من باید بیشتر از 3 کلمه باشد.'),
            validators.MaxLengthValidator(500, 'مهارت های من باید کمتر از 200 کلمه باشد')
        ],
        required=False,
        max_length=500,
        min_length=1,
        help_text="مهارت های خود را بنویسید ( با , از هم جدا کنید )"
    )


class ChangeUserPasswordForm(forms.Form):
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'id': 'password1', 'placeholder': 'رمز عبور را وارد کنید'}),
        label='رمز عبور',
        validators=[
            validators.MinLengthValidator(12, 'رمز عبور باید  12 کلمه باشد.'),
            validators.MaxLengthValidator(12, 'رمز عبور باید 12 کلمه باشد')
        ],
        required=True,
        max_length=12,
        min_length=12,
        help_text=html.format_html(
            '<div class="help"><ul class="list-unstyled text-secondary"><li>گذرواژه شما نمی‌تواند شبیه سایر اطلاعات شخصی شما باشد.</li><li>رمز عبور شما می‌بایست حداقل از 8 حرف تشکیل شده باشد.</li><li>گذرواژه شما نمی تواند یک گذرواژه معمول باشد.</li><li>گذرواژه شما نمی تواند کلا عدد باشد</li></ul></div>')

    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'id': 'password2', 'placeholder': 'تکرار رمز عبور را وارد کنید'}),
        label='تکرار رمز عبور',
        validators=[
            validators.MinLengthValidator(12, 'تکرار رمز عبور باید  12 کلمه باشد.'),
            validators.MaxLengthValidator(12, 'تکرار رمز عبور باید  12 کلمه باشد')
        ],
        required=True,
        max_length=12,
        min_length=12,
        help_text="برای تائید، رمز عبور قبلی را وارد کنید."
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password2 != password1:
            raise forms.ValidationError('رمز عبور و تکرار آن، یکی نیستند')
        else:
            return password1


class EditArticleForm(forms.Form):
    STATUS = (
        ('n', None),
        ('u', 'منتشر نشود'),
        ('w', 'درحال بررسی'),
        ('p', 'منتشر شود'),
    )
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='عنوان', required=False)
    content = forms.CharField(widget=TinyMCE(attrs={'required': False, 'cols': 40, 'rows': 20}), label='محتوا',
                              required=False)
    image = forms.ImageField(label='تصویر اصلی', required=False, help_text='ابعاد 440*750')
    video_url = forms.URLField(
        widget=forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://www.aparat.com/v/MACWd'}),
        label='لینک ویدیو آپارات', required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(attrs={"class": 'custom-select mb-3'}), label='دسته بندی ها',
                                      required=False)
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                         widget=forms.SelectMultiple(attrs={"class": 'custom-select mb-3'}),
                                         label='تگ ها',

accounts_app/templates/dashboard/base.html
{% if request.user.is_superuser %}
    {% load static %}
    {% load render_partial %}
    <!DOCTYPE html>
    <html lang="fa">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}

            {% endblock %}
        </title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block head_css %}

        {% endblock %}
        {% block head_script %}

        {% endblock %}
        <!-- Font Awesome -->
        {% include 'dashboard/header_referenced.html' %}
    </head>
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        {% render_partial 'accounts_app.views.dashboard_header' %}
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        {% render_partial 'accounts_app.views.admin_sidebar' %}

        <!-- Content Wrapper. Contains page content -->
        {% block content %}

        {% endblock %}
        <!-- /.content-wrapper -->
        {% render_partial 'accounts_app.views.dashboard_footer' %}

        <!-- Control Sidebar -->

        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    {% include 'dashboard/footer_referenced.html' %}
    {% block script %}

    {% endblock %}
    </body>
    </html>

{% endif %}

accounts_app/templates/dashboard/create_gallery.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block head_css %}

{% endblock %}
{% block head_script %}

{% endblock %}
{% block title %}
    ایجاد گالری
{% endblock %}
{% block content %}
    <div class="content-wrapper" style="min-height: 1222px;">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-10 col-md-2 mb-2">
                        <h1 class="m-0 text-dark">ایجاد گالری</h1>
                    </div>
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- Small boxes (Stat box) -->
                    <div class="row">
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    <form action="{% url 'create-gallery' %}" method="post"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button class="btn btn-success" type="submit">ذخیره</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

accounts_app/templates/dashboard/edit-article.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}
    ویرایش پست
{% endblock %}
{% block head_css %}
{% endblock %}
{% block head_script %}
    <script src="{% static 'tinymce/tinymce.min.js' %}" referrerpolicy="origin"></script>
{% endblock %}
{% block content %}
    <div class="content-wrapper" style="min-height: 1222px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ article.title }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/">خانه</a></li>
                            <li class="breadcrumb-item active">ویرایش پست</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">

                <div class="col-md-12">
                    <div class="form-control">
                        <div class="form-group">
                            <form role="form" method="post" enctype="multipart/form-data"
                                  action="{% url 'edit-article' article.id %}">
                                {% csrf_token %}                                <!-- text input -->
                                <div class="form-group">
                                    <label for="creator">نویسنده</label>
                                    <input type="text" id="creator" disabled class="form-control"
                                            {% if article.creator.get_full_name %}
                                           value="{{ article.creator.get_full_name }}"
                                            {% else %}
                                           value="{{ article.creator }}"
                                            {% endif %}>
                                </div>
                                <div class="form-group">
                                    <label for="date-created">تاریخ ایجاد</label>
                                    <input type="text" id="date-created" disabled class="form-control"
                                           value="{{ article.date_created.year }}/{{ article.date_created.month }}/{{ article.date_created.day }}">
                                </div>
                                <div class="form-group">
                                    <label for="date-update">تاریخ آخرین بروزرسانی</label>
                                    <input type="text" id="date-update" disabled class="form-control"
                                           value="{{ article.date_update.year }}/{{ article.date_update.month }}/{{ article.date_update.day }}">
                                </div>
                                <div class="form-group">
                                    <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                                    {{ form.title }}
                                </div>
                                <!-- textarea -->
                                <div class="form-group">
                                    <label for="{{ form.content.id_for_label }}">{{ form.content.label }}</label>
                                    {{ form.content }}
                                </div>
                                <div class="form-group">
                                    <label for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
                                    {{ form.image }}
                                    <p class="mt-1">{{ form.image.help_text }}</p>
                                </div>

                                <!-- input states -->
                                <div class="form-group has-success">
                                    <label class="control-label" for="{{ form.video_url.id_for_label }}"><i
                                            class="fa fa-link px-1"></i>{{ form.video_url.label }}</label>
                                    {{ form.video_url }}
                                </div>
                                <div class="form-group has-warning">
                                    <label class="control-label" for="{{ form.category.id_for_label }}"><i
                                            class="fa fa-caret-left"></i> {{ form.category.label }} <a
                                            class="btn btn-primary" href="{% url 'create-category' %}">ایجاد</a></label>
                                    {{ form.category }}
                                </div>
                                <div class="form-group has-error">
                                    <label class="control-label" for="{{ form.tag.id_for_label }}"><i
                                            class="fa fa-caret-left"></i> {{ form.tag.label }} <a
                                            class="btn btn-primary" href="{% url 'create-tag' %}">ایجاد</a></label>
                                    {{ form.tag }}
                                    <p class="mt-1">{{ form.tag.help_text }}</p>
                                </div>

                                <!-- checkbox -->
                                <div class="form-group">
                                    <div class="form-check">
                                        <label class="control-label" for="{{ form.status.id_for_label }}"><i
                                                class="fa fa-caret-left"></i> {{ form.status.label }}</label>
                                        {{ form.status }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input class="btn btn-success" type="submit" value="ذخیره">
                                </div>
                            </form>
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                </div>


                <!-- /. box -->
            </div>
            <!-- /.col -->
        </section>
    </div>
{% endblock %}
{% block script %}
    <script>
        tinymce.init({
            selector: '#id_content'
        });
    </script>

{% endblock %}

accounts_app/templates/dashboard/gallery_list.html
{% extends 'dashboard/base.html' %}
{% block head_css %}
{% endblock %}
{% block head_script %}

{% endblock %}
{% block title %}
    گالری
{% endblock %}
{% block content %}
    {% if request.user.is_superuser %}
        <div class="content-wrapper" style="min-height: 1222px;">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>گالری</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-left">
                                <li class="breadcrumb-item"><a href="/">خانه</a></li>
                                <li class="breadcrumb-item active">گالری لیست</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">گالری<span><a class="mx-2" href="{% url 'create-gallery' %}"><button
                                            class="btn btn-primary">ایجاد گالری جدید </button></a></span></h3>
                                </div>
                                <!-- /.card-header -->
                                {% if galleries %}
                                    <div class="card-body">
                                        <table class="table table-bordered">
                                            <tbody>
                                            <th class="text-center">ویرایش</th>
                                            <th class="text-center">پست</th>
                                            <th class="text-center">حذف</th>
                                            {% for gallery in galleries %}
                                                <tr class="text-center">
                                                    <td><a href="{% url 'edit-gallery' gallery.id %}"
                                                           class="text-success"><i
                                                            class="mx-2 fa fa-edit"></i></a></td>
                                                    <td>
                                                        <a target="_blank"
                                                           href="{% url 'blog:article_detail' gallery.article.id gallery.article.get_slug_title %}">{{ gallery.article.title }}</a>
                                                    </td>
                                                    <td><a href="{% url 'remove-gallery' gallery.id %}"
                                                           class="text-danger"><i
                                                            class="mx-2 fa fa-remove"></i></a></td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% else %}
                                    <p class="alert alert-warning text-center">گالری موجود نیست</p>
                                {% endif %}
                                <!-- /.card-body -->
                            </div>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
    {% else %}
        <p class="alert alert-danger text-center">دسترسی برای شما فعال نمی باشد</p>
    {% endif %}
{% endblock %}
{% block script %}
{% endblock %}