aboutUs_app/urls.py
from django.urls import path
from aboutUs_app.views import about_us

app_name = 'about'
urlpatterns = [
    path('', about_us, name='about-us'),
]

api/urls.py
from django.urls import path

from api.views import ArticleListApiView, ArticleDetailApiView, ArticleUpdateApiView, ArticleDeleteApiView, \
    CreateArticleApiView

app_name = 'api'
urlpatterns = [
    path('', ArticleListApiView.as_view(), name='api-article-list'),
    path('create-article/', CreateArticleApiView.as_view(), name='api-create-article'),
    path('<int:pk>/', ArticleDetailApiView.as_view(), name='api-article-detail'),
    path('<int:pk>/update/', ArticleUpdateApiView.as_view(), name='api-article-update'),
    path('<int:pk>/delete/', ArticleDeleteApiView.as_view(), name='api-article-delete'),
]

blog_app/urls.py
from django.urls import path

from blog_app.views import ArticleListView, article_detail_view, Search, GetByCategory, GetByTag

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('<int:article_id>/<title>/', article_detail_view, name='article_detail'),
    path('search/', Search.as_view(), name='search'),
    path('categories/<slug:category_name>/', GetByCategory.as_view(), name='get_category'),
    path('tags/<slug:tag_name>/', GetByTag.as_view(), name='get_tag'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('', home_page, name='home-page'),
    path('accounts/', include('accounts_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('about-us/', include('aboutUs_app.urls')),
    path('contact-us/', include('contact_us_app.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact_us_app/urls.py
from django.urls import path

from contact_us_app.views import contact_us

app_name = 'contact'
urlpatterns = [
    path('', contact_us, name='contact-us'),
]

templates/Base/Footer.html
{% load static %}
<footer class="footer-area bg-gray pt-100 pb-70 text-right" dir="rtl">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4">
                <div class="copyright mb-30">
                    <div class="footer-logo">
                        <a href="/">
                            <img alt="{{ setting.name }}" src="{{ setting.logo.url }}" width="103" height="26">
                        </a>
                    </div>
                    <p><a href="#" class="font-weight-bold">{{ setting.name }}</a><br>{{ setting.copy_right }}<br>
                        <span>{{ now_year.year }} ©</span></p>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4">
                <div class="footer-widget mb-30 ml-30">
                    <div class="footer-title">
                        <h3>درباره ما</h3>
                    </div>
                    <div class="footer-list">
                        <ul>
                            <li><a href="{% url 'about:about-us' %}">درباره ما</a></li>
                            <li><a href="{% url 'contact:contact-us' %}">تماس با ما</a></li>
                            <li><a href="{% url 'blog:article_list' %}">آموزش ها</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="footer-widget mb-30 ml-75">
                    <div class="footer-title">
                        <h3>شبکه های ما</h3>
                    </div>
                    <div class="footer-list">
                        <ul>
                            {% for social_network in setting.socialnetwork_set.all %}
                                <li><a target="_blank" href="{{ social_network.url }}">{{ social_network.name }}</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 mb-5" dir="rtl">
                <div class="footer-widget mb-30 ml-70">
                    <div class="footer-title">
                        <h3>عضویت در خبرنامه</h3>
                    </div>
                    <div class="subscribe-style" dir="rtl">
                        <p dir="rtl" class="">لطفا برای خبر دار شدن از جدید ترین آموزش ها، ایمیل خود را وارد کنید .</p>
                        <div id="mc_embed_signup" class="subscribe-form">
                            <form id="mc-embedded-subscribe-form" class="validate" method="post">
                                {% csrf_token %}
                                <div id="mc_embed_signup_scroll" class="mc-form">
                                    {{ form.email }}
                                    {% for error in form.email.errors %}
                                        <p class="alert alert-danger">{{ error }}</p>
                                    {% endfor %}

                                    <div class="clear text-center">
                                        <input id="mc-embedded-subscribe" class="button" type="submit" name="subscribe"
                                               value="عضویت">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/Base/Header.html
<header class="header-area header-padding-1 sticky-bar header-res-padding clearfix">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-6 col-4">
                <div class="logo">
                    <a href="/">
                        <img alt="" src="assets/img/logo/logo.png">
                    </a>
                </div>
            </div>
            <div class="col-xl-8 col-lg-8 d-none d-lg-block">
                <div class="main-menu">
                    <nav>
                        <ul dir="rtl">
                            <li><a href="/">خانه </a>
                            </li>
                            <li><a href="{% url 'blog:article_list' %}">وبلاگ </a>
                            </li>
                            <li><a href="{% url 'about:about-us' %}"> درباره ما </a></li>
                            <li><a href="{% url 'contact:contact-us' %}"> تماس با ما</a></li>
                            {% if  request.user.is_superuser %}
                                <li><a class="text-success" href="{% url 'dashboard' %}"> پنل ادمین</a></li>
                                <li><a class="text-primary" href="{% url 'api:api-article-list' %}"> API</a></li>
                                <li><a class="text-primary" href="{% url 'logout' %}"> خروج</a></li>
                            {% elif request.user.is_authenticated %}
                                <li><a class="text-primary" href="{% url 'logout' %}"> خروج</a></li>
                            {% else %}
                                <li><a class="text-danger" href="{% url 'dashboard' %}"> ورود</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-xl-2 col-lg-2 col-md-6 col-8 text-right">
                <div class="header-right-wrap">
                    <div class="same-style header-search">
                        <a class="search-active" href="#"><i class="pe-7s-search"></i></a>
                        <div class="search-content">
                            <form action="{% url 'blog:search' %}">
                                <input type="text" name="query" value="{{ request.GET.query }}"
                                       placeholder="...جستوجو کنید"/>
                                <button class="button-search"><i class="pe-7s-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mobile-menu-area">
        <div class="mobile-menu">
            <nav id="mobile-menu-active">
                <ul class="menu-overflow">
                    <li><a href="/">خانه</a>
                    </li>
                    <li><a href="{% url 'blog:article_list' %}">وبلاگ</a>
                    </li>
                    <li><a href="{% url 'about:about-us' %}">درباره ما</a></li>
                    <li><a href="{% url 'contact:contact-us' %}">تماس با ما</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

templates/Base/base.html
{% load render_partial %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}

    {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block seo %}
        <meta name="description" content="">
    {% endblock %}
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.fav_icon.url }}">

    <!-- CSS
	============================================ -->
    {% include 'Base/headerReferenced.html' %}
</head>

<body>
{% render_partial 'config.views.header' %}
{% block content %}

{% endblock %}
{% render_partial 'config.views.footer' %}

<!-- JS
============================================ -->

{% include 'Base/footerReferenced.html' %}

</body>

</html>

templates/Base/footerReferenced.html
{% load static %}
<!-- jQuery JS -->
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<!-- Plugins JS -->
<script src="{% static 'assets/js/plugins.js' %}"></script>
<!-- Ajax Mail -->
<script src="{% static 'assets/js/ajax-mail.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'assets/js/main.js' %}"></script>

templates/Base/headerReferenced.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
<!-- google font -->
<link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/Nab-Bold.css' %}">
<!-- Icon Font CSS -->
<link rel="stylesheet" href="{% static 'assets/css/icons.min.css' %}">
<!-- Plugins CSS -->
<link rel="stylesheet" href="{% static 'assets/css/plugins.css' %}">
<!-- Main Style CSS -->
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<!-- Modernizer JS -->
<script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>