api/urls.py
from django.urls import path

from api.views import ArticleListApiView, ArticleDetailApiView, ArticleUpdateApiView, ArticleDeleteApiView, \
    CreateArticleApiView

app_name = 'api'
urlpatterns = [
    path('', ArticleListApiView.as_view(), name='api-article-list'),
    path('create-article/', CreateArticleApiView.as_view(), name='api-create-article'),
    path('<int:pk>/', ArticleDetailApiView.as_view(), name='api-article-detail'),
    path('<int:pk>/update/', ArticleUpdateApiView.as_view(), name='api-article-update'),
    path('<int:pk>/delete/', ArticleDeleteApiView.as_view(), name='api-article-delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('', home_page, name='home-page'),
    path('accounts/', include('accounts_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('about-us/', include('aboutUs_app.urls')),
    path('contact-us/', include('contact_us_app.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact_us_app/urls.py
from django.urls import path

from contact_us_app.views import contact_us

app_name = 'contact'
urlpatterns = [
    path('', contact_us, name='contact-us'),
]

contact_us_app/models.py
from django.db import models
from django_jalali.db import models as jmodels


# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=25, verbose_name='نام و نام خانوادگی', blank=True, null=True)
    email = models.EmailField(verbose_name='ایمیل', blank=True, null=True)
    subject = models.CharField(max_length=1000, verbose_name='عنوان تماس', blank=True, null=True)
    message = models.TextField(verbose_name='پیغام', blank=True, null=True)
    date_send = jmodels.jDateTimeField(verbose_name='تاریخ ارسال', blank=True, null=True)

    class Meta:
        verbose_name = 'تماس کاربر'
        verbose_name_plural = 'تماس های کاربران'

    def __str__(self):
        return self.name

site_settings_app/models.py
from django.db import models


# Create your models here.

class Setting(models.Model):
    logo = models.ImageField(upload_to='logos/', verbose_name='لوگوی سایت', help_text='26 * 103', blank=True, null=True)
    fav_icon = models.ImageField(upload_to='icons/', blank=True, null=True, verbose_name='فاو آیکون',
                                 help_text='80 * 80')
    name = models.CharField(max_length=1000, verbose_name='نام سایت', blank=True, null=True)
    copy_right = models.CharField(max_length=200000, verbose_name='نوشته قانون کی رایت', blank=True, null=True)

    class Meta:
        verbose_name = 'تنظیم سایت'
        verbose_name_plural = 'تنظیمات سایت'

    def __str__(self):
        return self.name


class Phone(models.Model):
    setting = models.ForeignKey(Setting, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=12, verbose_name='شماره تلفن', blank=True, null=True)

    class Meta:
        verbose_name = 'شماره تلفن'
        verbose_name_plural = 'تلفن های سایت'

    def __str__(self):
        return self.phone_number


class Email(models.Model):
    setting = models.ForeignKey(Setting, on_delete=models.CASCADE)
    email = models.EmailField(verbose_name='ایمیل', blank=True, null=True)

    class Meta:
        verbose_name = 'ایمیل سایت'
        verbose_name_plural = 'ایمیل های سایت'

    def __str__(self):
        return self.email


class Address(models.Model):
    setting = models.ForeignKey(Setting, on_delete=models.CASCADE)
    address = models.TextField(verbose_name='آدرس', blank=True, null=True)

    class Meta:
        verbose_name = 'آدرس'
        verbose_name_plural = 'آدرس  های شرکت'

    def __str__(self):
        return self.setting.name


class SocialNetwork(models.Model):
    setting = models.ForeignKey(Setting, on_delete=models.CASCADE)
    name = models.CharField(max_length=10000, verbose_name='نام شبکه', blank=True, null=True)
    url = models.URLField(verbose_name='آدرس اینترنتی', blank=True, null=True)

    class Meta:
        verbose_name = 'شبکه سایت'
        verbose_name_plural = 'شبکه های سایت'

    def __str__(self):
        return self.name


class SeoHomePage(models.Model):
    title = models.CharField(max_length=100, verbose_name='title', blank=True, null=True)
    keywords = models.CharField(max_length=100, verbose_name='keywords', blank=True, null=True)
    description = models.TextField(verbose_name='description', blank=True, null=True)

    class Meta:
        verbose_name = 'سئو'
        verbose_name_plural = 'سثو صفحه ی اصلی'

    def __str__(self):
        return self.title

contact_us_app/forms.py
from django import forms
from django.core import validators


class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "نام و نام خانوادگی *"}),
        validators=[
            validators.MaxLengthValidator(25, 'تعداد کلمات نام و نام خانوادگی شما نباید بیشتر از 25 کلمه باشد'),
            validators.MinLengthValidator(3, 'تعداد کلمات نام و نام خانوادگی شما نباید کمتر از 3 کلمه باشد'),
        ]
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'ایمیل *'}),
        validators=[
            validators.EmailValidator()
        ]
    )

    subject = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "عنوان تماس *"}),
        validators=[
            validators.MaxLengthValidator(40, 'تعداد کلمات عنوان تماس نباید بیشتر از 40  کلمه باشد'),
            validators.MinLengthValidator(3, 'تعداد کلمات عنوان تماس نباید کمتر از 3 کلمه باشد'),
        ]
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "پیغام *"}),
    )

contact_us_app/views.py
import datetime
from django.shortcuts import render, redirect

# Create your views here.
from contact_us_app.forms import ContactForm
from contact_us_app.models import Contact
from site_settings_app.models import Setting


def contact_us(request):
    setting = Setting.objects.last()
    form = ContactForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data.get('name')
        email = form.cleaned_data.get('email')
        subject = form.cleaned_data.get('subject')
        message = form.cleaned_data.get('message')

        new_contact = Contact.objects.create(name=name, email=email, subject=subject, message=message,
                                             date_send=datetime.datetime.now())
        if new_contact is not None:
            new_contact.save()
            return redirect('contact:contact-us')
        form = ContactForm()

    context = {
        'form': form,
        'setting': setting,
    }
    return render(request, 'contact/contact.html', context)

contact_us_app/templates/contact/contact.html
{% extends 'Base/base.html' %}
{% block seo %}

{% endblock %}
{% block title %}
    تماس با ما
{% endblock %}
{% block content %}
    <div class="breadcrumb-area pt-35 pb-35 bg-gray-3">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <ul>
                    <li class="active">تماس با ما</li>
                    <li>
                        <a href="/">خانه</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container my-5" dir="rtl">
        <div class="custom-row-2">
            <div class="col-lg-4 col-md-5">
                <div class="contact-info-wrap">
                    <div class="single-contact-info">
                        <div class="contact-icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="contact-info-dec mx-1">
                            {% for phone in setting.phone_set.all %}
                                <p>{{ phone.phone_number }}</p>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="single-contact-info">
                        <div class="contact-icon">
                            <i class="fa fa-globe"></i>
                        </div>
                        <div class="contact-info-dec mx-1">
                            {% for email in setting.email_set.all %}
                                <p><a href="mailto:{{ email.email }}">{{ email.email }}</a></p>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="single-contact-info text-right">
                        <div class="contact-icon">
                            <i class="fa fa-map-marker"></i>
                        </div>
                        <div class="contact-info-dec mx-1">
                            {% for address in setting.address_set.all %}
                                <p>{{ address.address }}</p>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="contact-social text-center">
                        <h3>ما را دنبال کنید</h3>
                        <ul>
                            {% for social_network in setting.socialnetwork_set.all %}
                                <li><a href="{{ social_network.url }}"><i class="fa fa-{{ social_network.name }}"></i></a></li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-7 text-right" dir="rtl">
                <div class="contact-form">
                    <div class="contact-title mb-30">
                        <h2>با ما تماس بگیرید</h2>
                    </div>
                    <form class="contact-form-style" id="contact-form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6">
                                {{ form.name }}
                                {% for error in form.name.errors %}
                                    <p class="alert alert-danger">{{ error }}</p>
                                {% endfor %}

                            </div>
                            <div class="col-lg-6">
                                {{ form.email }}
                                {% for error in form.email.errors %}
                                    <p class="alert alert-danger">{{ error }}</p>
                                {% endfor %}
                            </div>
                            <div class="col-lg-12">
                                {{ form.subject }}
                                {% for error in form.subject.errors %}
                                    <p class="alert alert-danger">{{ error }}</p>
                                {% endfor %}
                            </div>
                            <div class="col-lg-12">
                                {{ form.message }}
                                {% for error in form.message.errors %}
                                    <p class="alert alert-danger">{{ error }}</p>
                                {% endfor %}
                                <button class="submit" type="submit">ارسال</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}