api/urls.py
from django.urls import path

from api.views import ArticleListApiView, ArticleDetailApiView, ArticleUpdateApiView, ArticleDeleteApiView, \
    CreateArticleApiView

app_name = 'api'
urlpatterns = [
    path('', ArticleListApiView.as_view(), name='api-article-list'),
    path('create-article/', CreateArticleApiView.as_view(), name='api-create-article'),
    path('<int:pk>/', ArticleDetailApiView.as_view(), name='api-article-detail'),
    path('<int:pk>/update/', ArticleUpdateApiView.as_view(), name='api-article-update'),
    path('<int:pk>/delete/', ArticleDeleteApiView.as_view(), name='api-article-delete'),
]

blog_app/urls.py
from django.urls import path

from blog_app.views import ArticleListView, article_detail_view, Search, GetByCategory, GetByTag

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('<int:article_id>/<title>/', article_detail_view, name='article_detail'),
    path('search/', Search.as_view(), name='search'),
    path('categories/<slug:category_name>/', GetByCategory.as_view(), name='get_category'),
    path('tags/<slug:tag_name>/', GetByTag.as_view(), name='get_tag'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('', home_page, name='home-page'),
    path('accounts/', include('accounts_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('about-us/', include('aboutUs_app.urls')),
    path('contact-us/', include('contact_us_app.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.db.models import Q
from django.utils import html
from tinymce.models import HTMLField
from django_jalali.db import models as jmodels
# Create your models here.
from config.settings import AUTH_USER_MODEL


class Category(models.Model):
    name = models.CharField(max_length=1000, verbose_name='دسته بندی', blank=True, null=True)
    slug = models.SlugField(max_length=1000, verbose_name='نام انگلیسی', help_text='برای مثال: category-name',
                            blank=True, null=True)

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=1000, verbose_name='دسته بندی', blank=True, null=True)
    slug = models.SlugField(max_length=1000, verbose_name='نام انگلیسی', help_text='برای مثال: tag-name', blank=True,
                            null=True)

    class Meta:
        verbose_name = "برچسب"
        verbose_name_plural = "برچسب ها"

    def __str__(self):
        return self.name


class ArticleManager(models.Manager):
    def get_search(self, query):
        lookup = (
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(category__name__icontains=query) |
                Q(tag__name__icontains=query)
        )
        return self.get_queryset().filter(lookup, status='p').distinct()


class Article(models.Model):
    STATUS = (
        ('u', 'منتشر نشود'),
        ('w', 'درحال بررسی'),
        ('p', 'منتشر شود'),
    )

    creator = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='نویسنده', blank=True,
                                null=True)
    title = models.CharField(max_length=1000, verbose_name='عنوان پست', blank=True, null=True)
    content = HTMLField(verbose_name='توضیحات', blank=True, null=True)
    image = models.ImageField(upload_to='blog/images/', verbose_name='تصویر پست', help_text="440 * 750", blank=True,
                              null=True)
    video_url = models.URLField(verbose_name='لینک ویدئو آپارات', default='', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='انتخاب دسته بندی', blank=True,
                                 null=True)
    tag = models.ManyToManyField(Tag, verbose_name='انتخاب برچسب', blank=True)
    date_created = jmodels.jDateTimeField(verbose_name='تاریخ ایجاد', blank=True, null=True, auto_now_add=True)
    date_update = jmodels.jDateTimeField(verbose_name='تاریخ بروزرسانی', blank=True, null=True, auto_now_add=True)
    status = models.CharField(max_length=1000, choices=STATUS, default='u', verbose_name='وضعیت', blank=True, null=True)
    visit_count = models.IntegerField(default=0, editable=False, verbose_name='تعداد بازدید', blank=True, null=True)

    objects = ArticleManager()

    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def get_image(self):
        if self.image:
            return html.format_html(f'<img src="{self.image.url}" width=100 height=100 style="border-radius: 5px" />')
        else:
            return None

    def get_video_url(self):
        return self.video_url.strip('https://www.aparat.com/v/')

    def get_slug_title(self):
        return self.title.replace(' ', '-')

    def get_all_visit_count(self):
        pass


class ArticleGallery(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='پست', blank=True, null=True)
    title = models.CharField(max_length=1000, verbose_name='عنوان', blank=True, null=True)
    image = models.ImageField(upload_to='article/gallery/', verbose_name='تصویر', blank=True, null=True,
                              help_text="353 * 466")

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = 'گالری'

    def __str__(self):
        return self.title


class ArticleComment(models.Model):
    STATUS = (
        ('a', 'قبول شود'),
        ('r', 'رد شود'),
    )
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='پست', blank=True, null=True)
    name = models.CharField(max_length=10000, verbose_name='نام و نام خانوادگی', blank=True, null=True)
    email = models.EmailField(verbose_name='ایمیل', blank=True, null=True)
    text = models.TextField(verbose_name='پیغام', blank=True, null=True)
    date_send = jmodels.jDateTimeField(verbose_name='تاریخ ارسال', blank=True, null=True)
    status = models.CharField(max_length=1000, choices=STATUS, default='r', verbose_name='وضعیت', blank=True, null=True)

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'

    def __str__(self):
        return self.email


class Seo(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, blank=True, null=True, verbose_name="پست")
    title = models.CharField(max_length=1000, verbose_name='title', blank=True, null=True)
    keywords = models.CharField(max_length=1000, verbose_name='keywords', blank=True, null=True)
    description = models.TextField(verbose_name='description', blank=True, null=True)

    class Meta:
        verbose_name = 'سئو'
        verbose_name_plural = 'سثو پست ها'

    def __str__(self):
        return self.article.title


class SeoArticleList(models.Model):
    title = models.CharField(max_length=1000, verbose_name='title', blank=True, null=True)
    keywords = models.CharField(max_length=10000, verbose_name='keywords', blank=True, null=True)
    description = models.TextField(verbose_name='description', blank=True, null=True)

    class Meta:
        verbose_name = 'سئو'
        verbose_name_plural = 'سثو صفحه ی لیست پست ها'

    def __str__(self):
        return self.title


class SuggestionPost(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='پست')

    class Meta:
        verbose_name = 'پست پیشنهادی'
        verbose_name_plural = 'پست های پیشنهادی مدیر'

    def __str__(self):
        return self.article.title

blog_app/forms.py
from django import forms
from django.core import validators

from blog_app.models import ArticleComment


class ArticleCommentForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": 'آدرس ایمیل'}),
        validators=[
            validators.EmailValidator
        ]
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": 'نام و نام خانوادگی'}),
        validators=[
            validators.MaxLengthValidator(25, 'طول نام و نام خانوادگی نباید بیشتر از 25 کلمه باشد.'),
            validators.MinLengthValidator(3, 'طول نام و نام خانوادگی نباید کمتر از 3 کلمه باشد.')
        ]
    )

    text = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": 'پیغام...'}),
    )

    article_id = forms.IntegerField(
        widget=forms.HiddenInput()
    )

blog_app/views.py
import datetime

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import ListView

from blog_app.forms import ArticleCommentForm
from blog_app.models import Article, Category, Tag, ArticleComment, Seo, SeoArticleList
from site_settings_app.models import Setting


class ArticleListView(ListView):
    model = Article
    template_name = "blog/article_list.html"
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.filter(status='p').all()
        # return Article.objects.filter(date_created__date=datetime.datetime.today())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        context['meta_tag'] = SeoArticleList.objects.last()
        context['setting'] = Setting.objects.last()
        return context


def article_detail_view(request, *args, **kwargs):
    article_id = kwargs['article_id']
    article = Article.objects.filter(id=article_id, status='p').exists()
    if not article:
        raise Http404()
    article = Article.objects.get(id=article_id, status='p')
    form = ArticleCommentForm(request.POST or None, initial={"article_id": article_id})
    if form.is_valid():
        email = form.cleaned_data.get('email')
        name = form.cleaned_data.get('name')
        text = form.cleaned_data.get('text')
        article_id = form.cleaned_data.get('article_id')
        article = Article.objects.filter(id=article_id).first()

        new_comment = ArticleComment.objects.create(email=email, name=name, text=text, article=article,
                                                    status='r', date_send=datetime.datetime.now())
        if new_comment is not None:
            new_comment.save()
            return redirect('blog:article_detail', article.id, article.get_slug_title())
        form = ArticleCommentForm()

    comments = ArticleComment.objects.filter(status='a', article=article).all()
    article.visit_count += 1
    article.save()
    meta_tag = Seo.objects.filter(article=article).last()
    setting = Setting.objects.last()
    context = {
        'article': article,
        'form': form,
        'comments': comments,
        'meta_tag': meta_tag,
        'setting': setting,
    }
    return render(request, 'blog/article_detail.html', context)


def sidebar(request):
    recent_articles = Article.objects.filter(status='p').order_by('-id').all()[:4]
    categories = Category.objects.all()
    tags = Tag.objects.all()
    setting = Setting.objects.last()
    context = {
        'recent_articles': recent_articles,
        'categories': categories,
        'tags': tags,
        'setting': setting,
    }
    return render(request, 'blog/sidebar.html', context)


class GetByCategory(ListView):
    template_name = 'blog/article_list.html'
    paginate_by = 4
    model = Article

    def get_queryset(self):
        category = self.kwargs['category_name']
        if category is not None:
            return Article.objects.filter(category__slug=category, status='p').all()
        else:
            return Article.objects.filter(status='p').all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GetByCategory, self).get_context_data(**kwargs)
        context['setting'] = Setting.objects.last()
        return context


class GetByTag(ListView):
    template_name = 'blog/article_list.html'
    paginate_by = 4
    model = Article

    def get_queryset(self):
        tag = self.kwargs['tag_name']
        if tag is not None:
            return Article.objects.filter(tag__slug=tag, status='p').all()
        else:
            return Article.objects.filter(status='p').all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(GetByTag, self).get_context_data(**kwargs)
        context['setting'] = Setting.objects.last()
        return context


class Search(ListView):
    template_name = 'blog/article_list.html'
    paginate_by = 4
    model = Article

    def get_queryset(self):
        request = self.request
        query = request.GET.get('query')
        if query is not None:
            return Article.objects.get_search(query=query)
        else:
            return Article.objects.filter(status='p').all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        context['setting'] = Setting.objects.last()
        return context

blog_app/templates/blog/article_detail.html
{% extends 'Base/base.html' %}
{% load render_partial %}
{% block seo %}
    <meta name="title" content="{{ meta_tag.title }}">
    <meta name="keywords" content="{{ meta_tag.keywords }}">
    <meta name="description" content="{{ meta_tag.description }}">
{% endblock %}
{% block title %}
    {{ article.title }}
{% endblock %}
{% block content %}
    <div class="breadcrumb-area pt-35 pb-35 bg-gray-3">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <ul>
                    <li class="active">جزئیات پست</li>
                    <li>
                        <a href="/">خانه</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Blog-area pt-100 pb-100 text-right" dir="rtl">
        <div class="container">
            <div class="row flex-row-reverse">
                <div class="col-lg-9">
                    <div class="blog-details-wrapper ml-20">
                        <div class="blog-details-top">
                            <div class="blog-details-img">
                                {% if article.video_url != None and article.video_url != '' %}
                                    <style>.h_iframe-aparat_embed_frame {
                                        position: relative;
                                    }

                                    .h_iframe-aparat_embed_frame .ratio {
                                        display: block;
                                        width: 100%;
                                        height: auto;
                                    }

                                    .h_iframe-aparat_embed_frame iframe {
                                        position: absolute;
                                        top: 0;
                                        left: 0;
                                        width: 100%;
                                        height: 100%;
                                    }</style>
                                    <div class="h_iframe-aparat_embed_frame"><span
                                            style="display: block;padding-top: 57%"></span>
                                        <iframe src="https://www.aparat.com/video/video/embed/videohash/{{ article.get_video_url }}/vt/frame"
                                                allowFullScreen="true" webkitallowfullscreen="true"
                                                mozallowfullscreen="true"></iframe>
                                    </div>
                                {% else %}
                                    <img alt="{{ article.title }}" width="750" height="440"
                                         src="{{ article.image.url }}">
                                {% endif %}
                            </div>
                            <div class="blog-details-content">
                                <div class="blog-meta-2 col-sm-12">
                                    <ul dir="ltr">
                                        <li>
                                            <span>منتشر شده در: </span>{{ article.date_created.year }}/{{ article.date_created.month }}/{{ article.date_created.day }}
                                        </li>
                                        <li>
                                            <span>آخرین بروزرسانی در: </span> {{ article.date_update.year }}/{{ article.date_update.month }}/{{ article.date_update.day }}
                                        </li>
                                        <li><i class="fa fa-comments-o mx-1"></i><a href="#">
                                            {% if article.commnet_set == None %}
                                                0
                                            {% else %}
                                                {{ articke.comment_set.count }}
                                            {% endif %} </a></li>
                                        <li><a href="#"><i class="fa fa-eye mx-1"></i>{{ article.visit_count }}</a></li>
                                    </ul>
                                </div>
                                <h3>{{ article.title }}</h3>
                                <p>{{ article.content|safe }}</p>
                            </div>
                        </div>
                        <div class="dec-img-wrapper">
                            <div class="row">
                                {% for articlegallery in article.articlegallery_set.all %}
                                    <div class="col-md-6">
                                        <div class="dec-img mb-50">
                                            <img height="353" width="466" alt="{{ articlegallery.title }}"
                                                 src="{{ articlegallery.image.url }}">
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                        {% if article.category %}
                            <div class="tag-share">
                                <div class="dec-tag">
                                    <h5>دسته بندی ها</h5>
                                    <ul>
                                        <li><a href="{% url 'blog:get_category' article.category.slug %}">
                                            {{ article.category.name }}

                                        </a></li>
                                    </ul>
                                </div>
                            </div>
                        {% endif %}
                        {% if article.tag %}
                            <div class="dec-tag mb-4">
                                <h5>برچسب ها</h5>
                                <ul>
                                    {% for tag in article.tag.all %}
                                        <li class="d-inline-block"><a href="{% url 'blog:get_tag' tag.slug %}">
                                            #{{ tag.name }}{% if forloop.last %}
                                        {% else %}،
                                        {% endif %}
                                        </a></li>
                                    {% endfor %}

                                </ul>
                            </div>
                        {% endif %}
                        <div class="blog-reply-wrapper mt-50">
                            <h4 class="blog-dec-title">ارسال نظر (<span class="text-danger mx-1">نظرات بعد از تائید مدیر سایت، منتشر می شود.</span>)
                            </h4>
                            <form class="blog-form" method="post">
                                {% csrf_token %}
                                {{ form.article_id }}
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="leave-form">
                                            {{ form.name }}
                                            {% for error in form.name.errors %}
                                                <p class="alert alert-danger">{{ error }}</p>
                                            {% endfor %}

                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="leave-form">
                                            {{ form.email }}
                                            {% for error in form.email.errors %}
                                                <p class="alert alert-danger">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="text-leave">
                                            {{ form.text }}
                                            {% for error in form.texts.errors %}
                                                <p class="alert alert-danger">{{ error }}</p>
                                            {% endfor %}
                                            <input type="submit" value="ارسال">
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <div class="blog-comment-wrapper mt-55">
                            <h4 class="blog-dec-title">نظرات : {{ comments.count }}</h4>
                            {% for comment in comments %}
                                <div class="single-comment-wrapper mt-35">
                                    <div class="blog-comment-img">
                                        <img src="https://www.shareicon.net/data/512x512/2015/09/18/103159_user_512x512.png"
                                             width="120" height="120" alt="user">
                                    </div>
                                    <div class="blog-comment-content mx-4">
                                        <h4>{{ comment.name }}</h4>
                                        <span>{{ comment.date_send.year }}/{{ comment.date_send.month }}/{{ comment.date_send.day }} </span>
                                        <p>{{ comment.text }} </p>
                                    </div>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                {% render_partial 'blog_app.views.sidebar' %}
            </div>
        </div>
    </div>
{% endblock %}

blog_app/templates/blog/sidebar.html
<div class="col-lg-3">
    <div class="sidebar-style">
        <div class="sidebar-widget">
            <h4 class="pro-sidebar-title">پست های تازه </h4>
            <div class="sidebar-project-wrap mt-30">
                {% for recent_article in recent_articles %}
                    <div class="single-sidebar-blog">
                        <div class="sidebar-blog-img">
                            {% if recent_article.image %}
                                <a href="{% url 'blog:article_detail' recent_article.id recent_article.get_slug_title %}"><img
                                    width="70" height="60" src="{{ recent_article.image.url }}"
                                    alt="{{ recent_article.title }}"></a>
                            {% endif %}
                        </div>
                        <div class="sidebar-blog-content mx-2">
                            <span>{{ recent_article.category.name }}</span>
                            <h4>
                                <a href="{% url 'blog:article_detail' recent_article.id recent_article.get_slug_title %}">{{ recent_article.title }}</a>
                            </h4>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
        {% if categories %}
            <div class="sidebar-widget mt-35">
            <h4 class="pro-sidebar-title">دسته بندی ها </h4>
            <div class="sidebar-widget-list mt-20 text-left">
                <ul>
                    {% for category in categories %}
                        <li>
                            <div class="sidebar-widget-list-left text-right">
                                <a href="{% url 'blog:get_category' category.slug %}">{{ category.name }} <span
                                        class="float-left">{{ category.article_set.count }}</span> </a>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        {% endif %}
        <div class="sidebar-widget mt-50">
            <h4 class="pro-sidebar-title">برچسب ها </h4>
            <div class="sidebar-widget-tag mt-25">
                <ul>
                    {% for tag in tags %}
                        <li><a href="{% url 'blog:get_tag' tag.slug %}">{{ tag.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</div>